image: maven:3-jdk-11

before_script:
  - apt-get update
  - apt-get upgrade -y
  - apt-get -y install make
  - apt-get -y install chromium
  - apt-get -y install chromium-driver

stages:          # List of stages for jobs, and their order of execution
  - build
  # - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn compile
    - echo "Compile complete."

# unit-test-job:   # This job runs in the test stage.
#   stage: test    # It only starts when the job in the build stage completes successfully.
#   script:
#     - echo "Running unit tests..."
#     - make test
#     - echo "Unit tests pass"
